/*
 * Jumpserver API Docs
 *
 * Jumpserver Restful api docs
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AssetPermissionUserRelation struct {
	Id int32 `json:"id,omitempty"`
	User string `json:"user"`
	UserDisplay string `json:"user_display,omitempty"`
	Assetpermission string `json:"assetpermission"`
	AssetpermissionDisplay string `json:"assetpermission_display,omitempty"`
}
