/*
 * Jumpserver API Docs
 *
 * Jumpserver Restful api docs
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Platform struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name"`
	Base string `json:"base,omitempty"`
	Charset string `json:"charset,omitempty"`
	Internal bool `json:"internal,omitempty"`
	Meta map[string]string `json:"meta,omitempty"`
	Comment string `json:"comment,omitempty"`
}
