/*
 * Jumpserver API Docs
 *
 * Jumpserver Restful api docs
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Node struct {
	Id string `json:"id,omitempty"`
	Key string `json:"key,omitempty"`
	Value string `json:"value,omitempty"`
	OrgId string `json:"org_id,omitempty"`
	Name string `json:"name,omitempty"`
	FullValue string `json:"full_value,omitempty"`
	OrgName string `json:"org_name,omitempty"`
}
