/*
 * Jumpserver API Docs
 *
 * Jumpserver Restful api docs
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GatewayWithAuth struct {
	Id          string `json:"id,omitempty"`
	Name        string `json:"name"`
	Ip          string `json:"ip"`
	Port        int32  `json:"port,omitempty"`
	Protocol    string `json:"protocol,omitempty"`
	Username    string `json:"username,omitempty"`
	Password    string `json:"password,omitempty"`
	PrivateKey  string `json:"private_key,omitempty"`
	PublicKey   string `json:"public_key,omitempty"`
	Domain      string `json:"domain"`
	IsActive    bool   `json:"is_active,omitempty"`
	DateCreated string `json:"date_created,omitempty"`
	DateUpdated string `json:"date_updated,omitempty"`
	CreatedBy   string `json:"created_by,omitempty"`
	Comment     string `json:"comment,omitempty"`
	OrgId       string `json:"org_id,omitempty"`
	OrgName     string `json:"org_name,omitempty"`
}
