/*
 * Jumpserver API Docs
 *
 * Jumpserver Restful api docs
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AdminUserAuth struct {
	Password string `json:"password,omitempty"`
	PrivateKey string `json:"private_key,omitempty"`
}
