/*
 * Jumpserver API Docs
 *
 * Jumpserver Restful api docs
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type FtpLog struct {
	Id string `json:"id,omitempty"`
	OrgId string `json:"org_id,omitempty"`
	User string `json:"user"`
	RemoteAddr string `json:"remote_addr,omitempty"`
	Asset string `json:"asset"`
	SystemUser string `json:"system_user"`
	Operate string `json:"operate"`
	Filename string `json:"filename"`
	IsSuccess bool `json:"is_success,omitempty"`
	DateStart time.Time `json:"date_start,omitempty"`
}
