/*
 * Jumpserver API Docs
 *
 * Jumpserver Restful api docs
 *
 * API version: v1
 * Contact: support@fit2cloud.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GatheredUser struct {
	Id            string `json:"id,omitempty"`
	Asset         string `json:"asset,omitempty"`
	Hostname      string `json:"hostname,omitempty"`
	Ip            string `json:"ip,omitempty"`
	Username      string `json:"username,omitempty"`
	DateLastLogin string `json:"date_last_login,omitempty"`
	IpLastLogin   string `json:"ip_last_login,omitempty"`
	Present       bool   `json:"present,omitempty"`
	DateCreated   string `json:"date_created,omitempty"`
	DateUpdated   string `json:"date_updated,omitempty"`
	OrgId         string `json:"org_id,omitempty"`
	OrgName       string `json:"org_name,omitempty"`
}
